Use safer & faster min/max functions
Two issues here. First, the default min/max that this is dependening on uses
min/max as a macro. That means the `min` call was actually evaluating `sqrt`
and float cast twice, with a minor perf penalty (unless the optimizer catches
it).

Second, not all environments have min/max available in the
global namespace (particularly platformio's native env). This avoids that
implicit dependency. Therefore this fixes:

```
<path_here>/StepperDriver/src/BasicStepperDriver.cpp:141:25: error: use of undeclared identifier 'min'; did you mean 'fmin'?
```

The original purpose of this diff was the second issue, but researching other
people running into this made me realize the first issue. So I went down a
different fix.

Another fix is just use native c++'s std::min and std::max, but that gets into
various arduino-cli related compiler complications.